### ISSUE TITLE
Failed to build backend due to error: Cannot find module 'knex/lib/dialects/postgres/schema/pg-tablecompiler'

### ISSUE THREAD

**Issue by mervinyan** [medusajs/medusa-eats#23]
The `yarn setup-db` command failed at the `build` stage due to the following error:
Error: Cannot find module 'knex/lib/dialects/postgres/schema/pg-tablecompiler'
![2024-08-07_06-58](https://github.com/user-attachments/assets/3666ec89-6815-48f1-8a28-4cec8f207be4)

I checked the `node_modules\knex\lib\dialects` folder didn't see the `postgres` folder however there is `pgnative` though
![2024-08-07_07-03](https://github.com/user-attachments/assets/d39d5f08-8556-452c-881f-f12bb19fdb03)

Below is the vesion info
![2024-08-07_07-06](https://github.com/user-attachments/assets/b8965738-1546-44a5-aca6-6e4c6d861c9e)

I tried clean install few times but still facing the same issue...has anyone encountered this issue? if so how do you solve it?

Thanks!

**Comment by mervinyan** [comment]
This error is gone now after I upgrade the yarn to v4
